-- MySQL Script generated by MySQL Workbench
-- Wed Sep 13 11:47:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swp391` ;

-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swp391` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
USE `swp391` ;

-- -----------------------------------------------------
-- Table `swp391`.`setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`setting` ;

CREATE TABLE IF NOT EXISTS `swp391`.`setting` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `type_id` INT NULL,
                                                  `setting_title` VARCHAR(45) NULL,
    `status` BIT(1) NULL,
    `create_by` INT NULL,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`user` ;

CREATE TABLE IF NOT EXISTS `swp391`.`user` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `email` VARCHAR(45) NULL,
    `phone` VARCHAR(45) NULL,
    `password` VARCHAR(45) NULL,
    `status` BIT(1) NULL,
    `full_name` VARCHAR(255) NULL,
    `gender` BIT(1) NULL,
    `date_of_birth` DATETIME NULL,
    `avatar_url` TEXT NULL,
    `role_id` INT NULL,
    `create_by` INT NULL,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `a_idx` (`role_id` ASC) VISIBLE,
    FOREIGN KEY (`role_id`)
    REFERENCES `swp391`.`setting` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`subject` ;

CREATE TABLE IF NOT EXISTS `swp391`.`subject` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `subject_manager_id` INT NULL,
                                                  `subject_name` VARCHAR(255) NULL,
    `subject_code` VARCHAR(45) NULL,
    `status` BIT(1) NULL,
    `description` VARCHAR(255) NULL,
    `create_by` INT NULL,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `subject_manager_id_idx` (`subject_manager_id` ASC) VISIBLE,
    FOREIGN KEY (`subject_manager_id`)
    REFERENCES `swp391`.`user` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


---------------------------------------- INSERT DATA ----------------------------------------
-- 1 = role
-- 2 = mail domain
-- 3 = semester

INSERT INTO setting(type_id,setting_title,status)
VALUES
    (1, "User",1),
    (1, "Admin",1),
    (1, "Subject manager",1),
    (1, "Class manager",1),
    (1, "Project mentor",1),
    (2, "gmail.com",1),
    (2, "fpt.edu.vn",1),
    (3, "SUMMER 23",1),
    (3, "FALL 23",1);

-- subject manager
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`gender`,`date_of_birth`,`avatar_url`,`role_id`)
VALUES
    ("gillianmorris@gmail.com","0224667148","123456","Gillian Morris",1,"2001-12-09","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",3),
    ("germanebaird3434@gmail.com","0820671142","123456","Germane Baird",0,"2003-07-21","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",3),
    ("kareemmacdonald4709@gmail.com","0318444787","123456","Kareem Macdonald",1,"2002-06-23","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",3),
    ("annedonovan3197@gmail.com","0137041646","123456","Anne Donovan",0,"2003-08-06","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",3),
    ("echonash7303@gmail.com","0534896566","123456","Echo Nash",1,"2002-01-19","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",3);

-- user
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`gender`,`date_of_birth`,`avatar_url`,`role_id`)
VALUES
    ("julianlester@gmail.com","0027829656","123456","Julian Lester",1,"2002-10-20","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("galvinbass4030@gmail.com","0037963572","123456","Galvin Bass",0,"2003-02-04","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("brianmassey@gmail.com","0436285872","123456","Brian Massey",1,"2002-08-11","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("judahcardenas5324@gmail.com","0681589922","123456","Judah Cardenas",0,"2002-02-04","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("kellyreyes9226@gmail.com","0363517319","123456","Kelly Reyes",1,"2003-03-26","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("kevinwilliam@gmail.com","0905521148","123456","Kevin William",0,"2003-07-09","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("lesleycastro@gmail.com","0571427370","123456","Lesley Castro",1,"2002-01-27","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("danarosario@gmail.com","0272326964","123456","Dana Rosario",0,"2003-05-16","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("aimeeewing@gmail.com","0636454167","123456","Aimee Ewing",1,"2002-07-27","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("amywalton@gmail.com","0858486104","123456","Amy Walton",0,"2001-11-29","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1);
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`gender`,`date_of_birth`,`avatar_url`,`role_id`)
VALUES
    ("rashadrush2211@gmail.com","0860113768","123456","Rashad Rush",1,"2002-01-21","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("elainelawrence@gmail.com","0721721061","123456","Elaine Lawrence",0,"2003-09-06","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("larissareese@gmail.com","0279994112","123456","Larissa Reese",1,"2003-02-11","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("holleemyers@gmail.com","0532678220","123456","Hollee Myers",0,"2003-04-16","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("xanthusmcfadden3684@gmail.com","0302569530","123456","Xanthus Mcfadden",1,"2002-11-18","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("mylesdavidson@gmail.com","0583590348","123456","Myles Davidson",0,"2002-06-25","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("teegansantana@gmail.com","0547146642","123456","Teegan Santana",1,"2001-09-28","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("elvisratliff@gmail.com","0911884338","123456","Elvis Ratliff",0,"2003-05-29","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("rowaningram@gmail.com","0734547525","123456","Rowan Ingram",1,"2002-07-08","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1),
    ("oraallen@gmail.com","0298393485","123456","Ora Allen",0,"2003-01-19","https://assets.stickpng.com/thumbs/585e4beacb11b227491c3399.png",1);


-- subject
INSERT INTO `subject` (`subject_manager_id`,`subject_name`,`subject_code`,`status`,`description`)
VALUES
    (1,"Software development project","SWP391",1,"This course focuses on designing, developing, and integrating the basic Web-based system/application using Java Web or .NET technologies."),
    (2,"Software Requirement","SWR302",1,"This course is a model-based introduction to RE, providing the conceptual background and terminology on RE, addressing a variety of techniques for requirements development."),
    (3,"Software Testing","SWT301",1,"esting techniques aimed at assuring that appropriate functionality has been implemented correctly in the software system or product."),
    (1,"Basic Cross-Platform Application Programming With .NET","PRN211",1,"Basic knowledge of Window Forms in .NET, ASP.NET Core MVC, RESTful API .NET"),
    (2,"Front-End web development with React","FER201m",1,"Learn front-end web development for implementing a multi-platform solution.");
