-- MySQL Script generated by MySQL Workbench
-- Wed Sep 13 11:47:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swp391` ;

-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swp391` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema swp391
-- -----------------------------------------------------
USE `swp391` ;

-- -----------------------------------------------------
-- Table `swp391`.`setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`setting` ;

CREATE TABLE IF NOT EXISTS `swp391`.`setting` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `type_id` INT NULL,
                                                  `setting_title` VARCHAR(45) NULL,
    `status` BIT(1) NULL DEFAULT 1,
    `display_order` INT ,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`user` ;

CREATE TABLE IF NOT EXISTS `swp391`.`user` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `email` VARCHAR(45) NULL,
    `phone` VARCHAR(45) NULL,
    `password` VARCHAR(45) NULL,
    `status` BIT(1) NULL DEFAULT 1,
    `note` VARCHAR(255),
    `full_name` VARCHAR(255) NULL,
    `avatar_url` TEXT NULL,
    `role_id` INT NULL,
    `token` varchar(255) DEFAULT NULL,
    `active` BIT(1) NULL DEFAULT 0,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `a_idx` (`role_id` ASC) VISIBLE,
    FOREIGN KEY (`role_id`)
    REFERENCES `swp391`.`setting` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`subject` ;

CREATE TABLE IF NOT EXISTS `swp391`.`subject` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `subject_manager_id` INT NULL,
                                                  `subject_name` VARCHAR(255) NULL,
    `subject_code` VARCHAR(45) NULL,
    `status` BIT(1) NULL DEFAULT 1,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `subject_manager_id_idx` (`subject_manager_id` ASC) VISIBLE,
    FOREIGN KEY (`subject_manager_id`)
    REFERENCES `swp391`.`user` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`assignment` ;

CREATE TABLE IF NOT EXISTS `swp391`.`assignment` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `subject_id` INT NULL,
                                                     `title` VARCHAR(45) NULL,
    `status` BIT(1) NULL DEFAULT 1,
    `description` VARCHAR(245) NULL,
    `is_subject_assignment` BIT(1) NULL,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `a_idx` (`subject_id` ASC) VISIBLE,
    FOREIGN KEY (`subject_id`)
    REFERENCES `swp391`.`subject` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`class` ;

CREATE TABLE IF NOT EXISTS `swp391`.`class` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `class_name` VARCHAR(245) NULL,
    `semester_id` INT NULL,
    `teacher_id` INT NULL,
    `status` BIT(1) NULL,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX ` a_idx` (`teacher_id` ASC) VISIBLE,
    INDEX `b_idx` (`semester_id` ASC) VISIBLE,
    FOREIGN KEY (`teacher_id`)
    REFERENCES `swp391`.`user` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
    FOREIGN KEY (`semester_id`)
    REFERENCES `swp391`.`setting` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`class_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`class_assignment` ;

CREATE TABLE IF NOT EXISTS `swp391`.`class_assignment` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `class_id` INT NULL,
                                                           `assignment_id` INT NULL,
                                                           `start_date` DATETIME NULL,
                                                           `end_date` DATETIME NULL,
                                                           `status` BIT(1) NULL,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `a_idx` (`class_id` ASC) VISIBLE,
    INDEX `b_idx` (`assignment_id` ASC) VISIBLE,
    FOREIGN KEY (`class_id`)
    REFERENCES `swp391`.`class` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
    FOREIGN KEY (`assignment_id`)
    REFERENCES `swp391`.`assignment` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`class_issue_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`class_issue_setting` ;

CREATE TABLE IF NOT EXISTS `swp391`.`class_issue_setting` (
                                                              `id` INT NOT NULL AUTO_INCREMENT,
                                                              `class_id` INT NULL,
                                                              `type` INT NULL,
                                                              `status` BIT(1) NULL,
    `work_processes` VARCHAR(155) NULL,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `a_idx` (`class_id` ASC) VISIBLE,
    FOREIGN KEY (`class_id`)
    REFERENCES `swp391`.`class` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`project` ;

CREATE TABLE IF NOT EXISTS `swp391`.`project` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `class_id` INT NULL,
                                                  `project_mentor_id` INT NULL,
                                                  `team_leader_id` INT NULL,
                                                  `title` VARCHAR(45) NULL,
    `status` BIT(1) NULL,
    `group_name` VARCHAR(45) NULL,
    `description` VARCHAR(200) NULL,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `a_idx` (`class_id` ASC) VISIBLE,
    INDEX `a_idx1` (`project_mentor_id` ASC) VISIBLE,
    INDEX `a_idx2` (`team_leader_id` ASC) VISIBLE,
    FOREIGN KEY (`class_id`)
    REFERENCES `swp391`.`class` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
    FOREIGN KEY (`project_mentor_id`)
    REFERENCES `swp391`.`user` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
    FOREIGN KEY (`team_leader_id`)
    REFERENCES `swp391`.`user` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swp391`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`student_class` ;

CREATE TABLE IF NOT EXISTS `swp391`.`student_class` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `student_id` INT NOT NULL,
                                                        `class_id` INT NOT NULL,
                                                        `project_id` INT NULL,
                                                        PRIMARY KEY (`id`, `student_id`, `class_id`),
    INDEX `b_idx` (`class_id` ASC) VISIBLE,
    INDEX `a_idx` (`project_id` ASC) VISIBLE,
    FOREIGN KEY (`student_id`)
    REFERENCES `swp391`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`class_id`)
    REFERENCES `swp391`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`project_id`)
    REFERENCES `swp391`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `swp391`.`subject_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391`.`subject_setting` ;

CREATE TABLE IF NOT EXISTS `swp391`.`subject_setting` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `subject_id` INT NULL,
                                                          `type_id` INT NULL,
                                                          `setting_title` VARCHAR(45) NULL,
    `status` BIT(1) NULL DEFAULT 1,
    `display_order` INT ,
    `create_by` INT NULL DEFAULT 0,
    `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` INT NULL DEFAULT 0,
    `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`subject_id`)
    REFERENCES `swp391`.`subject` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


---------------------------------------- INSERT DATA ----------------------------------------
-- 1 = role
-- 2 = mail domain
-- 3 = semester

INSERT INTO setting(type_id,setting_title,display_order)
VALUES
    (1, "Student",4),
    (1, "Admin",1),
    (1, "Subject manager",2),
    (1, "Teacher",3),
    (2, "gmail.com",1),
    (2, "fpt.edu.vn",2),
    (3, "SUMMER 23",1),
    (3, "FALL 23",2);

-- admin
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`role_id`, `active`, `avatar_url`)
VALUES
    ("admin@gmail.com","0999999999","21232f297a57a5a743894a0e4a801fc3","Admin",2,1,"/images/user_icon.png"),
    ("subject@gmail.com","0999999998","e10adc3949ba59abbe56e057f20f883e","Subject manager",3,1,"/images/user_icon.png"),
    ("class@gmail.com","0999999997","e10adc3949ba59abbe56e057f20f883e","Class manager",4,1,"/images/user_icon.png"),
    ("leader@gmail.com","0999999997","e10adc3949ba59abbe56e057f20f883e","Team leader",1,1,"/images/user_icon.png"),
    ("mentor@gmail.com","0999999997","e10adc3949ba59abbe56e057f20f883e","Project mentor",4,1,"/images/user_icon.png");

-- user
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`avatar_url`,`role_id`, `active`)
VALUES
    ("julianlester@gmail.com","0027829656","e10adc3949ba59abbe56e057f20f883e","Julian Lester","/images/user_icon.png",1,1),
    ("galvinbass4030@gmail.com","0037963572","e10adc3949ba59abbe56e057f20f883e","Galvin Bass","/images/user_icon.png",1,1),
    ("brianmassey@gmail.com","0436285872","e10adc3949ba59abbe56e057f20f883e","Brian Massey","/images/user_icon.png",1,1),
    ("judahcardenas5324@gmail.com","0681589922","e10adc3949ba59abbe56e057f20f883e","Judah Cardenas","/images/user_icon.png",1,1),
    ("kellyreyes9226@gmail.com","0363517319","e10adc3949ba59abbe56e057f20f883e","Kelly Reyes","/images/user_icon.png",1,1),
    ("kevinwilliam@gmail.com","0905521148","e10adc3949ba59abbe56e057f20f883e","Kevin William","/images/user_icon.png",1,1),
    ("lesleycastro@gmail.com","0571427370","e10adc3949ba59abbe56e057f20f883e","Lesley Castro","/images/user_icon.png",1,1),
    ("danarosario@gmail.com","0272326964","e10adc3949ba59abbe56e057f20f883e","Dana Rosario","/images/user_icon.png",1,1),
    ("aimeeewing@gmail.com","0636454167","e10adc3949ba59abbe56e057f20f883e","Aimee Ewing","/images/user_icon.png",1,1),
    ("amywalton@gmail.com","0858486104","e10adc3949ba59abbe56e057f20f883e","Amy Walton","/images/user_icon.png",1,1);
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`avatar_url`,`role_id`, `active`)
VALUES
    ("rashadrush2211@gmail.com","0860113768","e10adc3949ba59abbe56e057f20f883e","Rashad Rush","/images/user_icon.png",1,1),
    ("elainelawrence@gmail.com","0721721061","e10adc3949ba59abbe56e057f20f883e","Elaine Lawrence","/images/user_icon.png",1,1),
    ("larissareese@gmail.com","0279994112","e10adc3949ba59abbe56e057f20f883e","Larissa Reese","/images/user_icon.png",1,1),
    ("holleemyers@gmail.com","0532678220","e10adc3949ba59abbe56e057f20f883e","Hollee Myers","/images/user_icon.png",1,1),
    ("xanthusmcfadden3684@gmail.com","0302569530","e10adc3949ba59abbe56e057f20f883e","Xanthus Mcfadden","/images/user_icon.png",1,1),
    ("mylesdavidson@gmail.com","0583590348","e10adc3949ba59abbe56e057f20f883e","Myles Davidson","/images/user_icon.png",1,1),
    ("teegansantana@gmail.com","0547146642","e10adc3949ba59abbe56e057f20f883e","Teegan Santana","/images/user_icon.png",1,1),
    ("elvisratliff@gmail.com","0911884338","e10adc3949ba59abbe56e057f20f883e","Elvis Ratliff","/images/user_icon.png",1,1),
    ("rowaningram@gmail.com","0734547525","e10adc3949ba59abbe56e057f20f883e","Rowan Ingram","/images/user_icon.png",1,1),
    ("oraallen@gmail.com","0298393485","e10adc3949ba59abbe56e057f20f883e","Ora Allen","/images/user_icon.png",1,1);
INSERT INTO `user` (`email`,`phone`,`password`,`full_name`,`avatar_url`,`role_id`, `active`)
VALUES
    ("a@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","a","/images/user_icon.png",1,1),
    ("b@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","b","/images/user_icon.png",1,1),
    ("c@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","c","/images/user_icon.png",1,1),
    ("d@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","d","/images/user_icon.png",1,1),
    ("e@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","e","/images/user_icon.png",1,1),
    ("f@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","f","/images/user_icon.png",1,1),
    ("g@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","g","/images/user_icon.png",1,1),
    ("h@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","h","/images/user_icon.png",1,1),
    ("i@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","i","/images/user_icon.png",1,1),
    ("k@gmail.com",NULL,"e10adc3949ba59abbe56e057f20f883e","k","/images/user_icon.png",1,1);

-- subject
INSERT INTO `subject` (`subject_manager_id`,`subject_name`,`subject_code`)
VALUES
    (2,"Software development project","SWP391"),
    (2,"Java Web Application Development","PRJ301"),
    (2,"Software Requirement","SWR302"),
    (4,"Software Testing","SWT301"),
    (4,"Basic Cross-Platform Application Programming With .NET","PRN211"),
    (4,"Front-End web development with React","FER201m");

-- subject_setting
INSERT INTO subject_setting(subject_id,type_id,setting_title,display_order)
VALUES
    (1 ,1 , "High",1),
    (1 ,1, "Medium",2),
    (1 ,1, "Low",3),
    (1 ,2, "High",1),
    (1 ,2, "Medium",2),
    (1 ,2, "Low",3),
    (2 ,1, "High",1),
    (2 ,1, "Medium",2),
    (2 ,2, "High",1),
    (2 ,2, "Medium",2),
    (2 ,2, "Low",3);

INSERT INTO `class` (`class_name`,`semester_id`,`teacher_id`,`status`)
VALUES
    ("SE1740",8,3,1),
    ("SE1741",8,3,1);

INSERT INTO project (class_id, project_mentor_id, team_leader_id, title, status,group_name,description)
VALUES
    (1, 5, 4, "Project A", 1, "Group A", "Web app with Servlet/JSP and Mysql"),
    (1, 5, 6, "Project B", 1, "Group A", "Web app with Servlet/JSP and Mysql"),
    (1, 5, 11, "Project C", 1, "Group A", "Web app with Servlet/JSP and Mysql"),
    (1, 5, 16, "Project D", 1, "Group A", "Web app with Servlet/JSP and Mysql"),
    (1, 5, 21, "Project E", 1, "Group A", "Web app with Servlet/JSP and Mysql"),
    (1, 5, 26, "Project F", 1, "Group A", "Web app with Servlet/JSP and Mysql");

INSERT INTO student_class (student_id, class_id, project_id)
VALUES
    (6, 1, 1),    -- Student 6 in Project 1
    (7, 1, 1),    -- Student 7 in Project 1
    (8, 1, 1),    -- Student 8 in Project 1
    (9, 1, 1),    -- Student 9 in Project 1
    (10, 1, 1),   -- Student 10 in Project 1
    (11, 1, 2),   -- Student 11 in Project 2
    (12, 1, 2),   -- Student 12 in Project 2
    (13, 1, 2),   -- Student 13 in Project 2
    (14, 1, 2),   -- Student 14 in Project 2
    (15, 1, 2),   -- Student 15 in Project 2
    (16, 1, 3),   -- Student 16 in Project 3
    (17, 1, 3),   -- Student 17 in Project 3
    (18, 1, 3),   -- Student 18 in Project 3
    (19, 1, 3),   -- Student 19 in Project 3
    (20, 1, 3),   -- Student 20 in Project 3
    (21, 1, 4),   -- Student 21 in Project 4
    (22, 1, 4),   -- Student 22 in Project 4
    (23, 1, 4),   -- Student 23 in Project 4
    (24, 1, 4),   -- Student 24 in Project 4
    (25, 1, 4),   -- Student 25 in Project 4
    (26, 1, 5),   -- Student 26 in Project 5
    (27, 1, 5),   -- Student 27 in Project 5
    (28, 1, 5),   -- Student 28 in Project 5
    (29, 1, 5),   -- Student 29 in Project 5
    (30, 1, 5),   -- Student 30 in Project 5
    (4, 1, 5),   -- Student 4 in Project 6
    (32, 1, 5),   -- Student 32 in Project 6
    (33, 1, 5),   -- Student 33 in Project 6
    (34, 1, 5),   -- Student 34 in Project 6
    (35, 1, 5);   -- Student 35 in Project 6

INSERT INTO assignment (`subject_id`,`title`,`description`,`is_subject_assignment`)
VALUES
    (1,'Review Iteration 1','Review docs and code iteration 1 all group',1),
    (1,'Review Iteration 2','Review docs and code iteration 2 all group',1),
    (1,'Review Iteration 3','Review docs and code iteration 3 all group',1);
